namespace Kermalis.PokemonGameEngine.Core
{
    public enum Flag : byte
    {
        Test0,
        Test1,
        Test2,
        Test3,
        Test4,
        Test5,
        Test6,
        Test7,
        Test8,
        Test9,
        Test10,
        Test11,
        Test12,
        Test13,
        Test14,
        Test15,
        Test16,
        Test17,
        Test18,
        Test19,
        MAX
    }

    public enum Var : byte
    {
        Test0,
        Test1,
        Test2,
        Test3,
        Test4,
        Test5,
        Test6,
        Test7,
        Test8,
        Test9,
        Test10,
        Test11,
        Test12,
        Test13,
        Test14,
        Test15,
        Test16,
        Test17,
        Test18,
        Test19,
        MAX
    }
}
