namespace Kermalis.PokemonGameEngine.Core
{
    public enum Flag : byte
    {
        Badge1,
        Badge2,
        Badge3,
        Badge4,
        Badge5,
        Badge6,
        Badge7,
        Badge8,
        Test_GroudonVisible,
        Test1,
        Test2,
        Test3,
        Test4,
        Test5,
        Test6,
        Test7,
        Test8,
        Test9,
        Test10,
        Test11,
        Test12,
        Test13,
        Test14,
        Test15,
        Test16,
        Test17,
        Test18,
        Test19,
        MAX
    }

    public enum Var : byte
    {
        /// <summary>Automatically set to the last EventObj the player interacted with</summary>
        LastTalked,
        Test1,
        Test2,
        Test3,
        Test_GroudonState,
        Test5,
        Test6,
        Test7,
        Test8,
        Test9,
        Test10,
        Test11,
        Test12,
        Test13,
        Test14,
        Test15,
        Test16,
        Test17,
        Test18,
        Test19,
        SpecialVar1,
        SpecialVar2,
        SpecialVar_Result,
        Friendship_Step_Counter,
        MAX
    }
}
